repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-illegal-windows-names
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: a95dde803518e8b723480f182c87bfb1d243d742  # frozen: v0.19.1
    hooks:
    -   id: markdownlint-cli2
        args:
          [
            "-c",
            ".markdownlint.jsonc",
            "content",
          ]
- repo: https://github.com/crate-ci/typos
  rev: 802d5794ff9cf7b15610c47eca99cd1ab757d8d4  # frozen: v1
  hooks:
    - id: typos

- repo: https://github.com/amperser/proselint/
  rev: a83a6164999803909f69eb3274d783c7070e73c1  # frozen: v0.16.0
  hooks:
    - id: proselint
      files: \.md
